#配置数据源
spring:
  datasource:
    druid:
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: 123456

      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"

    dynamic:
      druid: # 全局druid参数，绝大部分值和默认保持一致。(现已支持的参数如下,不清楚含义不要乱设置)
        # 初始化连接大小
        initial-size: 5
        max-active: 20
        # 最小空闲连接数
        min-idle: 5
        max-wait: 30000
        # 可关闭的空闲连接间隔时间
        time-between-eviction-runs-millis: 60000
        time-between-log-stats-millis:
        stat-sqlmax-size:
        # 配置连接在池中的最小生存时间
        min-evictable-idle-time-millis: 30000
        max-evictable-idle-time-millis:
        use-global-datasource-stat:
        async-init:
        clear-filters-enable:
        reset-stat-enable:
        not-full-timeout-retry-count:
        max-wait-thread-count:
        fail-fast:
        phyTimeout-millis:
        keep-alive: true
        # 打开PSCache，并且指定每个连接上PSCache的大小
        pool-prepared-statements: true
        max-open-prepared-statements: 20
        max-pool-prepared-statement-per-connection-size: 20
        init-variants:
        init-global-variants:
        use-unfair-lock:
        kill-when-socket-read-timeout:
        connection-properties:
        init-connection-sqls:
        share-prepared-statements:
        connection-errorretry-attempts:
        break-after-acquire-failure:
        # 配置监控统计拦截的filters
        filters: stat,wall # 注意这个值和druid原生不一致，默认启动了stat,wall
      primary: data_eladmin
      datasource:
        data_eladmin:
          # type: com.alibaba.druid.pool.DruidDataSource
          username: ncc
          password: ncc
          driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
          url: jdbc:log4jdbc:mysql://localhost:3306/eladmin?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
          druid: # 全局druid参数，绝大部分值和默认保持一致。(现已支持的参数如下,不清楚含义不要乱设置)
            # 初始化连接大小
            initial-size: 1
            max-active: 1
            # 最小空闲连接数
            min-idle: 1
            max-wait: 30000
            test-while-idle: false
            test-on-borrow: false
            test-on-return: false
            validation-query: select '1'
            validation-query-timeout: 30000
        data_meta:
          # type: com.alibaba.druid.pool.DruidDataSource
          username: ncc
          password: ncc
          driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
          url: jdbc:log4jdbc:mysql://localhost:3306/meta?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
          druid: # 全局druid参数，绝大部分值和默认保持一致。(现已支持的参数如下,不清楚含义不要乱设置)
            # 初始化连接大小
            initial-size: 1
            max-active: 1
            # 最小空闲连接数
            min-idle: 1
            max-wait: 30000
            test-while-idle: false
            test-on-borrow: false
            test-on-return: false
            validation-query: select '1'
            validation-query-timeout: 30000

  #配置 Jpa
  jpa:
      hibernate:
      # 生产环境设置成 none，避免程序运行时自动更新数据库结构
      ddl-auto: none

#jwt
jwt:
  header: Authorization
  secret: mySecret
  # token 过期时间 2个小时
  expiration: 7200000
  auth:
    # 授权路径
    login: /login
    # 路径
    signin: /signin
    # 获取用户信息
    account: /info

#是否允许生成代码，生产环境设置为false
generator:
  enabled: true